before_install:
  - git fetch --tags

language: scala
scala:
    - 2.12.12
    - 2.13.3

service:
    - redis-server

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    # stage="test" if no stage is specified
    - name: compile
      script: sbt compile
    # run ci-release only if previous stages passed
    - stage: release
      script: sbt ci-release